"""Canonical machine-readable error codes for Worktree operations."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Canonical machine-readable error codes for Worktree operations."""

    # Config
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"
    CONFIG_MALFORMED_JSON = "CONFIG_MALFORMED_JSON"
    CONFIG_SCHEMA_INVALID = "CONFIG_SCHEMA_INVALID"
    CONFIG_ROOT_NOT_OBJECT = "CONFIG_ROOT_NOT_OBJECT"
    CONFIG_PATH_IS_DIRECTORY = "CONFIG_PATH_IS_DIRECTORY"
    CONFIG_UNREADABLE = "CONFIG_UNREADABLE"
    CONFIG_PROTECTED_KEY = "CONFIG_PROTECTED_KEY"

    # Git
    GIT_NOT_REPO = "GIT_NOT_REPO"
    GIT_BINARY_MISSING = "GIT_BINARY_MISSING"
    GIT_DIRTY_WORKTREE = "GIT_DIRTY_WORKTREE"
    GIT_LOCK_ACTIVE = "GIT_LOCK_ACTIVE"
    GIT_DETACHED_HEAD = "GIT_DETACHED_HEAD"

    # Filesystem
    FS_UNWRITABLE = "FS_UNWRITABLE"
    FS_NOT_FOUND = "FS_NOT_FOUND"
    FS_PATH_EXISTS = "FS_PATH_EXISTS"

    # Sandbox
    SANDBOX_NOT_FOUND = "SANDBOX_NOT_FOUND"
    SANDBOX_STALE = "SANDBOX_STALE"
    SANDBOX_ORPHAN = "SANDBOX_ORPHAN"
    SANDBOX_PATH_CONFLICT = "SANDBOX_PATH_CONFLICT"
    SANDBOX_CREATION_FAILED = "SANDBOX_CREATION_FAILED"

    # Catalog
    CATALOG_NOT_FOUND = "CATALOG_NOT_FOUND"
    CATALOG_INVALID_NAME = "CATALOG_INVALID_NAME"
    CATALOG_SYNTAX_ERROR = "CATALOG_SYNTAX_ERROR"
    CATALOG_SCHEMA_INVALID = "CATALOG_SCHEMA_INVALID"

    # Diff / Patch
    DIFF_NOT_FOUND = "DIFF_NOT_FOUND"
    DIFF_READ_FAILED = "DIFF_READ_FAILED"
    PATCH_EMPTY = "PATCH_EMPTY"
    PATCH_SIZE_EXCEEDED = "PATCH_SIZE_EXCEEDED"
    PATCH_CORRUPT = "PATCH_CORRUPT"
    PATCH_FILE_COUNT_EXCEEDED = "PATCH_FILE_COUNT_EXCEEDED"
    PATCH_BINARY_DISALLOWED = "PATCH_BINARY_DISALLOWED"

    # Doctor
    DOCTOR_CHECK_CRASH = "DOCTOR_CHECK_CRASH"
    DOCTOR_BINARY_MISSING = "DOCTOR_BINARY_MISSING"
    DOCTOR_AGENT_KEY_MISSING = "DOCTOR_AGENT_KEY_MISSING"
    DOCTOR_AGENT_NO_MODEL = "DOCTOR_AGENT_NO_MODEL"
